Repository prgrms-web-devcourse/Team_17TOP_Film_BE, pull requests merged in 2021-12, with the labels that each got.

#7 [Film/#3] AWS S3에 이미지를 업로드하는 service 추가
  .gitignore
  film-api/build.gradle
  film-api/src/main/resources/application.yaml
  film-common/src/main/java/com/programmers/film/common/error/exception/ErrorCode.java
  film-external/build.gradle
  film-external/src.iml
  film-external/src/main/java/com/programmers/film/FilmExternernalRoot.java
  film-external/src/main/java/com/programmers/film/img/S3Service.java
  film-external/src/main/java/com/programmers/film/img/controller/ImgUploadController.java
  film-external/src/test/java/com/programmers/film/SpringBootExternalTest.java
Labels: Priority: High, Type: Feature/Function

#23 [Film/#18] add map function
  build.gradle
  film-api/src/main/java/com/programmers/film/api/config/WebSecurityConfigure.java
  film-api/src/main/java/com/programmers/film/api/post/controller/MapController.java
  film-api/src/main/java/com/programmers/film/api/post/controller/PostController.java
  film-api/src/main/java/com/programmers/film/api/post/converter/PointConverter.java
  film-api/src/main/java/com/programmers/film/api/post/converter/PostConverter.java
  film-api/src/main/java/com/programmers/film/api/post/dto/common/OrderImage.java
  film-api/src/main/java/com/programmers/film/api/post/dto/common/SimplePostDto.java
  film-api/src/main/java/com/programmers/film/api/post/dto/response/GetMapResponse.java
  film-api/src/main/java/com/programmers/film/api/post/service/MapService.java
  film-api/src/main/java/com/programmers/film/api/post/service/PostService.java
  film-api/src/main/resources/application-security.yaml
  film-api/src/main/resources/application.yaml
  film-common/build.gradle
  film-domain/build.gradle
  film-domain/src/main/java/com/programmers/film/domain/common/domain/BaseEntity.java
  film-domain/src/main/java/com/programmers/film/domain/post/repository/PostAuthorityRepository.java
  film-domain/src/main/java/com/programmers/film/domain/user/repository/UserRepository.java
  film-external/build.gradle
Labels: Priority: High, Type: Feature/Function

#56 [film/#52] 엿보기 응답 authorNickname추가
  film-api/src/main/java/com/programmers/film/api/post/converter/PostConverter.java
  film-api/src/main/java/com/programmers/film/api/post/dto/response/PreviewPostResponse.java
Labels: Priority: Critical, Type: Feature/Function

#64 fix: change error logic
  film-api/src/main/java/com/programmers/film/api/post/controller/PostController.java
  film-api/src/main/java/com/programmers/film/api/post/converter/PostConverter.java
  film-api/src/main/java/com/programmers/film/api/post/service/PostService.java
  film-common/src/main/java/com/programmers/film/common/error/GlobalExceptionHandler.java
Labels: Priority: Low, Type: Feature/Function

#69 [film/#59] docs: PostDelete, PostPreview, Maps restdocs
  film-api/src/docs/asciidoc/index.adoc
  film-api/src/main/java/com/programmers/film/api/post/dto/response/MapResponse.java
  film-api/src/test/java/com/programmers/film/api/post/controller/MapControllerTest.java
  film-api/src/test/java/com/programmers/film/api/post/controller/PostControllerTest.java
Labels: Priority: Low, Type: Feature/Document

#71 docs: add docs, controller Test
  film-api/src/docs/asciidoc/index.adoc
  film-api/src/main/java/com/programmers/film/api/post/dto/request/CreatePostRequestString.java
  film-api/src/main/java/com/programmers/film/api/post/dto/response/GetPostDetailResponse.java
  film-api/src/main/java/com/programmers/film/scheduler/Scheduler.java
  film-api/src/test/java/com/programmers/film/api/post/controller/PostControllerTest.java
  jffi9332566955833821941.dylib
Labels: Priority: High
